// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenshotAPI.Data;

#nullable disable

namespace ScreenshotAPI.Migrations
{
    [DbContext(typeof(ScanDbContext))]
    partial class ScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ScreenshotAPI.Models.ScanResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompetitorLinksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Found")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsMatchedUrlLive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedPageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ScreenshotBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanResults");
                });
#pragma warning restore 612, 618
        }
    }
}
